module.exports = {
  '@tag': ['articles'],
  'User should be able to update articles': (browser) => {
    browser
      .url('http://localhost:9090')
      .pause(2000)
      .waitForElementVisible('[datatest="signin-button"]')
      .assert.visible('[datatest="signin-button"]')
      .click('[datatest="signin-button"]')
      .pause(500)
      .assert.visible('[data-test="signin-form"]')
      .pause(1000)
      .setValue('#email', 'ngwobiachukwudi@gmail.com')
      .pause(200)
      .setValue('#password', 'P@ssword123')
      .pause(200)
      .click('[datatest="loginButton"]')
      .pause(3000)
      .url('http://localhost:9090/articles/data-test')
      .pause(3000)
      .assert.visible('div[class="read-article"]')
      .pause(500)
      .assert.visible('[data-test="edit-article"]')
      .pause(1000)
      .click('[data-test="edit-article"]')
      .pause(2000)
      .waitForElementVisible('input[name="title"]')
      .setValue('input[name="title"]', 'Lorem Ipsum')
      .pause(500)
      .waitForElementVisible('[data-placeholder="Tell us your story..."]')
      .setValue('[data-placeholder="Tell us your story..."]', 'This is the edited body')
      .pause(500)
      .assert.visible('[datatest="edit-ready"]')
      .click('[datatest="edit-ready"]')
      .pause(500)
      .setValue('input[id=file]', '/Users/chux/Documents/Screenshot 2019-09-10 at 00.23.36.png')
      .pause(4000)
      .assert.visible('input[class="tag-input-field"]')
      .setValue('input[class="tag-input-field"]', 'lorem ipsum tags ')
      .pause(1000)
      .assert.visible('textarea[name="description"]')
      .setValue('textarea[name="description"]', 'Thanks guys for watching to this point. Happy reviewing!!!')
      .pause(1000)
      .assert.visible('[datatest="publish-final"]')
      .click('[datatest="publish-final"]')
      .pause(2000)
      .end();
  },
};
